# environment setup

language: swift
os: osx
osx_image: xcode11.3.1
xcode_project: TravisFastlane.xcodeproj
xcode_scheme: TravisFastlane

# run jobs on changes only to development and master

branches:
  only:
    - development
    - master
    
# perform setup

install:
  - bundle install

# jobs and stages to run

jobs:
    include:
    - name: “Build Release”
      script: fastlane build_release --verbose
