
default_platform(:ios)

platform :ios do
  
  desc "This lane will deploy the app to TestFlight."
  lane :build_release do
    
    xcode_project = "TravisFastlane.xcodeproj"
    ipa_name = "Release" + ".ipa"
  
    puts "Xcode Project: " + xcode_project
    puts "IPA Name: " + ipa_name
    
    match(
      type: "appstore",
      readonly: true,
      app_identifier: "com.levi.TravisFastlane"
    )

    build_app(
      project: xcode_project,
      configuration: "Release",
      scheme: "TravisFastlane",
      silent: false,
      clean: false,
      output_directory: "fastlane/builds",
      output_name: ipa_name,
      export_method: "app-store",
      export_options: {
        "provisioningProfiles": {
          "com.levi.TravisFastlane" => "Travis Fastlane Distribution"
        }
      }
    )
    end

  end