
default_platform(:ios)

platform :ios do
  
  desc "This lane will deploy the app to TestFlight."
  lane :build_release do
    
    xcode_project = "TravisFastlane.xcodeproj"
    build_number = get_build_number(xcodeproj: xcode_project)
    ipa_name = "Release" + "_" + build_number + ".ipa"
  
    puts "Xcode Project: " + xcode_project
    puts "Build Number: " + build_number
    puts "Version Number: " + version_number
    puts "IPA Name: " + ipa_name

    build_app(
      project: xcode_project,
      configuration: "Release",
      scheme: "TravisFastlane",
      silent: false,
      clean: false,
      output_directory: "fastlane/builds",
      output_name: ipa_name
    )
    end

  end